export const ALL_FEATURES = [
    { key: 'durata_interventi', name: 'Durata degli interventi', checked: true, description: 'Calcola quanto tempo ogni speaker parla in totale. \n Esempio: { "speaker_1": 35.2 sec, "speaker_2": 20.1 sec }. \n Misura il bilanciamento della conversazione.' },
    { key: 'frequenza_interventi', name: 'Frequenza degli interventi', checked: true, description: 'Conteggio del numero di turni di parola per ogni speaker. \n Esempio: { "speaker_1": 12 turni, "speaker_2": 8 turni }. \n Chi prende più spesso la parola' },
    { key: 'pausa_tra_interventi', name: 'Pausa tra interventi', checked: true, description: 'Calcola la durata media delle pause tra un intervento e l\'altro. \n Esempio: { "pausa_media": 1.2 sec }. \n Misura la velocità della conversazione' },
    { key: 'sovrapposizione_parlato', name: 'Sovrapposizione del parlato', checked: true, description: 'Calcola la percentuale di sovrapposizione del parlato tra i due speaker. \n Esempio: { "overlap_percentage": 5.3% }. \n Misura il grado di interruzione tra i due speaker' },
    { key: 'emozioni_parlato', name: 'Emozioni nel parlato', checked: true, description: 'Riconosce le emozioni nel parlato. \n Esempio: { "speaker_1": "felice", "speaker_2": "triste" }. \n Misura il tono emotivo della conversazione' },
    { key: 'variazione_prosodia', name: 'Variazione della prosodia', checked: true, description: 'Riconosce le variazioni della prosodia nel parlato...' },
    { key: 'tempo_risposta', name: 'Tempo di risposta', checked: true, description: 'Calcola il tempo medio tra una domanda del medico e la risposta del paziente...' },
    { key: 'lunghezza_media_frasi', name: 'Lunghezza media delle frasi', checked: true, description: 'Calcola la lunghezza media delle frasi di ogni speaker...' },
    { key: 'ripetizione_ecolalia', name: 'Ripetizione e ecolalia', checked: true, description: 'Riconosce la ripetizione di parole o frasi...' },
    { key: 'complessita_sintattica', name: 'Complessità sintattica', checked: true, description: 'Calcola la complessità sintattica delle frasi di ogni speaker...' },
    { key: 'velocita_parlato', name: 'Velocità del parlato (Speech Rate)', checked: true, description: 'Calcola il numero medio di parole pronunciate al secondo da ogni speaker...' },
    { key: 'articolazione_pronuncia', name: 'Articolazione e pronuncia', checked: true, description: 'Riconosce la presenza di errori di pronuncia o di articolazione...' },
    { key: 'intonazione_stress_vocale', name: 'Intonazione e stress vocale', checked: true, description: 'Riconosce la presenza di intonazioni anomale o di stress vocale...' },
    { key: 'disfluenze', name: 'Disfluenze (Um, Eh, Ripetizioni)', checked: true, description: 'Riconosce la presenza di disfluenze nel parlato...' },
    { key: 'coordinazione_turn_taking', name: 'Coordinazione del turn-taking (dinamica conversazionale)', checked: true, description: 'Calcola la coordinazione del turn-taking tra i due speaker...' },
    { key: 'modulazione_energia_vocale', name: 'Modulazione dell’energia vocale', checked: true, description: 'Riconosce la presenza di variazioni nell’energia vocale...' },
    { key: 'analisi_armoniche_hnr', name: 'Analisi delle armoniche (HNR - Harmonics-to-Noise Ratio)', checked: true, description: 'Calcola il rapporto tra le armoniche e il rumore nel segnale vocale...' },
    { key: 'tempo_latenza_intra_turno', name: 'Tempo di latenza intra-turno', checked: true, description: 'Calcola il tempo medio di latenza all\'interno di un turno di parola...' },
    { key: 'frequenza_parole_funzionali', name: 'Frequenza delle parole funzionali', checked: true, description: 'Calcola la frequenza delle parole funzionali (articoli, preposizioni, congiunzioni)...' },
    { key: 'prevedibilita_entropia_parlato', name: 'Misura della prevedibilità (Entropia del parlato)', checked: true, description: 'Calcola l\'entropia del parlato di ogni speaker...' },
];

export const ALL_PARAMETERS = [
    { "name": "TALD totale", scale:[1,5], "checked": true, "description": "Misura totale del disturbo del linguaggio." },
    { "name": "Circostanzialità", scale:[1,5], "checked": true, "description": "Discorso eccessivamente dettagliato e prolisso, con difficoltà a giungere al punto." },
    { "name": "Deragliamento", scale:[1,5], "checked": true, "description": "Passaggio improvviso da un argomento all'altro senza connessione logica." },
    { "name": "Tangenzialità", scale:[1,5], "checked": true, "description": "Risposte non direttamente collegate alla domanda posta." },
    { "name": "Dissociazione del pensiero", scale:[1,5], "checked": true, "description": "Perdita di coerenza nel discorso, frasi sconnesse tra loro." },
    { "name": "Diafonia", scale:[1,5], "checked": true, "description": "Sovrapposizione di voci o discorsi tra più persone." },
    { "name": "Perseveranza", scale:[1,5], "checked": true, "description": "Ripetizione insistente di parole o concetti." },
    { "name": "Verbigerazione", scale:[1,5], "checked": true, "description": "Ripetizione continua di parole o frasi prive di significato contestuale." },
    { "name": "Rottura del pensiero", scale:[1,5], "checked": true, "description": "Interruzione improvvisa e senza motivo apparente del flusso di pensiero." },
    { "name": "Discorso sotto pressione", scale:[1,5], "checked": true, "description": "Flusso rapido e incontrollato di parole." },
    { "name": "Logorrea", scale:[1,5], "checked": true, "description": "Eccessiva verbosità e incapacità di fermarsi nel discorso." },
    { "name": "Discorso manieristico", scale:[1,5], "checked": true, "description": "Uso di parole o espressioni in modo artificioso o inusuale." },
    { "name": "Parafasia semantica", scale:[1,5], "checked": true, "description": "Sostituzione di una parola con un'altra con significato simile o correlato." },
    { "name": "Parafasia fonemica", scale:[1,5], "checked": true, "description": "Errori fonetici nelle parole pronunciate." },
    { "name": "Neologismi", scale:[1,5], "checked": true, "description": "Creazione di parole nuove e inesistenti nel linguaggio comune." },
    { "name": "Clandore-squillio", scale:[1,5], "checked": true, "description": "Uso di toni di voce inappropriati o eccessivamente accentuati." },
    { "name": "Ecolalia", scale:[1,5], "checked": true, "description": "Ripetizione automatica di parole o frasi pronunciate da altri." },
    { "name": "Povertà del contenuto del discorso", scale:[1,5], "checked": true, "description": "Discorso vago e privo di informazioni significative." },
    { "name": "Pensiero ristretto", scale:[1,5], "checked": true, "description": "Fissazione su un numero limitato di argomenti o idee." },
    { "name": "Pensiero rallentato", scale:[1,5], "checked": true, "description": "Lentezza nella formulazione e nell'esposizione dei pensieri." },
    { "name": "Povertà di parola", scale:[1,5], "checked": true, "description": "Riduzione significativa della quantità di parole usate." },
    { "name": "Concretismo", scale:[1,5], "checked": true, "description": "Difficoltà nel comprendere concetti astratti o metaforici." },
    { "name": "Blocco/i", scale:[1,5], "checked": true, "description": "Interruzione improvvisa del flusso del pensiero senza ripresa immediata." },
    { "name": "Ruminazione", scale:[1,5], "checked": true, "description": "Ripetizione costante di pensieri senza una conclusione." },
    { "name": "Povertà di pensiero", scale:[1,5], "checked": true, "description": "Difficoltà nel generare nuovi pensieri o idee." },
    { "name": "Pensiero inibito", scale:[1,5], "checked": true, "description": "Sensazione di blocco mentale con difficoltà a esprimersi." },
    { "name": "Disfunzione del linguaggio ricettivo", scale:[1,5], "checked": true, "description": "Difficoltà nella comprensione del linguaggio parlato o scritto." },
    { "name": "Disfunzione del linguaggio espressivo", scale:[1,5], "checked": true, "description": "Difficoltà nell'esprimere i propri pensieri in modo chiaro." },
    { "name": "Disf. iniziativa pensiero e intenzione", scale:[1,5], "checked": true, "description": "Difficoltà nell'avviare o mantenere un pensiero strutturato." },
    { "name": "Interferenza di pensiero", scale:[1,5], "checked": true, "description": "Pensieri intrusivi che disturbano il flusso del discorso." },
    { "name": "Pressione/impeto di pensieri", scale:[1,5], "checked": true, "description": "Flusso continuo e incontrollato di pensieri." }
];